/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A Solana account.
 *
 * All fields map 1-to-1 to the on-chain `Account` layout.
 * `lamports` and `rentEpoch` are `bigint` to avoid precision loss.
 */
export interface JsAccount {
  /** Lamports held by the account. */
  lamports: bigint
  /** Raw account data bytes. */
  data: Buffer
  /** Base58 public key of the program that owns this account. */
  owner: string
  /** Whether the account holds a loaded executable program. */
  executable: boolean
  /** Epoch at which this account will next owe rent. */
  rentEpoch: bigint
}
/** A `(pubkey, account)` pair — the input unit for `processInstruction`. */
export interface AccountEntry {
  /** Base58 public key. */
  pubkey: string
  /** The account state. */
  account: JsAccount
}
/** Per-account metadata within an instruction. */
export interface JsAccountMeta {
  /** Base58 public key. */
  pubkey: string
  /** Whether this account must sign the transaction. */
  isSigner: boolean
  /** Whether the instruction may mutate this account. */
  isWritable: boolean
}
/** A Solana instruction ready to be handed to `processInstruction`. */
export interface JsInstruction {
  /** Base58 public key of the program being invoked. */
  programId: string
  /** Ordered list of accounts the instruction references. */
  accounts: Array<JsAccountMeta>
  /** Raw instruction data bytes. */
  data: Buffer
}
/** Final state of a single account after execution. */
export interface ResultAccount {
  /** Base58 public key. */
  pubkey: string
  /** Lamports after execution. */
  lamports: bigint
  /** Account data bytes after execution. */
  data: Buffer
  /** Owner program public key (base58) after execution. */
  owner: string
  /** Whether the account is executable after execution. */
  executable: boolean
  /** Rent epoch. */
  rentEpoch: bigint
}
/** The complete outcome of a processed instruction. */
export interface InstructionResult {
  /** Human-readable program result: `"success"` or an error description. */
  programResult: string
  /** `true` when the program returned `Ok(())`. */
  success: boolean
  /** Compute units consumed during execution. */
  computeUnitsConsumed: bigint
  /** Wall-clock execution time in nanoseconds. */
  executionTime: bigint
  /** Bytes written by `set_return_data` (empty `Buffer` if none). */
  returnData: Buffer
  /**
   * Final state of every account provided to the instruction, in the
   * same order they were passed in.
   */
  resultingAccounts: Array<ResultAccount>
}
/** The outcome of a full transaction (multiple instructions processed atomically). */
export interface TransactionResult {
  /** Human-readable result of the last / failing instruction. */
  programResult: string
  /** `true` when all instructions succeeded. */
  success: boolean
  /** If a failure occurred, the 0-based index of the failing instruction. */
  failingInstructionIndex?: number
  /** Total compute units consumed across all instructions. */
  computeUnitsConsumed: bigint
  /** Wall-clock execution time in nanoseconds. */
  executionTime: bigint
  /** Bytes written by `set_return_data` in the last instruction that produced them. */
  returnData: Buffer
  /** Final state of every account provided, in the order they were passed. */
  resultingAccounts: Array<ResultAccount>
}
/**
 * A single validation assertion to run against an `InstructionResult`.
 *
 * Use the `check*` factory functions rather than constructing this directly.
 *
 * ```ts
 * import { checkSuccess, checkComputeUnits, checkAccountLamports } from 'svmforge';
 *
 * mollusk.processAndValidateInstruction(ix, accounts, [
 *   checkSuccess(),
 *   checkComputeUnits(500n),
 *   checkAccountLamports(ALICE, 999_000_000n),
 * ]);
 * ```
 */
export interface JsCheck {
  /** Discriminant: `"success"` | `"err"` | `"compute_units"` | `"return_data"` | `"account"`. */
  kind: string
  /** Expected `ProgramError::Custom` error code (for kind = `"err"`). */
  errorCode?: number
  /** Expected exact CU count (for kind = `"compute_units"`). */
  computeUnits?: bigint
  /** Expected return-data bytes (for kind = `"return_data"`). */
  returnData?: Buffer
  /** Target account pubkey (for kind = `"account"`). */
  pubkey?: string
  /** Expected lamports (for kind = `"account"`). */
  lamports?: bigint
  /** Expected owner pubkey base58 (for kind = `"account"`). */
  owner?: string
  /** Expected account data bytes (for kind = `"account"`). */
  data?: Buffer
  /** Expected executable flag (for kind = `"account"`). */
  executable?: boolean
  /** Expected data length in bytes (for kind = `"account"`). */
  space?: number
  /** When `true`, asserts the account was closed / does not exist (for kind = `"account"`). */
  closed?: boolean
}
/** Assert the program returned `Ok(())`. */
export declare function checkSuccess(): JsCheck
/** Assert the program returned `ProgramError::Custom(code)`. */
export declare function checkErr(errorCode: number): JsCheck
/** Assert the instruction consumed exactly `units` compute units. */
export declare function checkComputeUnits(units: bigint): JsCheck
/** Assert the instruction produced exactly `data` as return data. */
export declare function checkReturnData(data: Buffer): JsCheck
/** Assert a resulting account's lamport balance. */
export declare function checkAccountLamports(pubkey: string, lamports: bigint): JsCheck
/** Assert a resulting account's owner program. */
export declare function checkAccountOwner(pubkey: string, owner: string): JsCheck
/** Assert a resulting account's raw data bytes. */
export declare function checkAccountData(pubkey: string, data: Buffer): JsCheck
/** Assert a resulting account's data length in bytes. */
export declare function checkAccountSpace(pubkey: string, space: number): JsCheck
/** Assert a resulting account's executable flag. */
export declare function checkAccountExecutable(pubkey: string, executable: boolean): JsCheck
/** Assert that a resulting account is closed (lamports == 0, data empty, owner = system). */
export declare function checkAccountClosed(pubkey: string): JsCheck
/**
 * Build a `JsAccount` owned by the system program with no data.
 *
 * ```ts
 * import { systemAccount } from 'svmforge';
 * const alice = systemAccount(1_000_000_000n);
 * ```
 */
export declare function systemAccount(lamports: bigint): JsAccount
/**
 * Build an account owned by `owner` with `space` bytes of zeroed data.
 *
 * ```ts
 * import { emptyAccount } from 'svmforge';
 * const pda = emptyAccount(MY_PROGRAM_ID, 165, rent_exempt_lamports);
 * ```
 */
export declare function emptyAccount(owner: string, space: number, lamports: bigint): JsAccount
/** Program ID for SPL Token (`TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`) */
export const SPL_TOKEN_PROGRAM_ID: string
/** Program ID for SPL Token-2022 (`TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb`) */
export const SPL_TOKEN_2022_PROGRAM_ID: string
/** Program ID for Associated Token Account (`ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`) */
export const ASSOCIATED_TOKEN_PROGRAM_ID: string
/** Program ID for SPL Memo (`MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr`) */
export const MEMO_PROGRAM_ID: string
/**
 * Lightweight Solana program test harness.
 *
 * Drives the SVM directly — no full validator, no AccountsDB, no Bank.
 * You provide accounts explicitly; execution is near-instant.
 *
 * ```ts
 * // Testing a custom program
 * const mollusk = new MolluskSvm(MY_PROGRAM_ID, 'target/deploy/my_program');
 *
 * // Testing a builtin (system program, token, etc.)
 * const mollusk = MolluskSvm.createDefault();
 * ```
 */
export declare class MolluskSvm {
  /**
   * Load a BPF program and create a test harness.
   *
   * @param programId   - Base58 public key of the program under test.
   * @param programPath - Path to the compiled ELF **without** the `.so`
   *                      extension (e.g. `"target/deploy/my_program"`).
   *                      Mollusk appends `.so` automatically and searches
   *                      `SBF_OUT_DIR` if the path is relative.
   */
  constructor(programId: string, programPath: string)
  /**
   * Create a harness with **no** custom program loaded.
   *
   * Useful when testing instructions that only use builtin programs
   * (system program, SPL token, compute-budget, etc.).
   */
  static createDefault(): MolluskSvm
  /** Execute a single instruction and return the full result. */
  processInstruction(instruction: JsInstruction, accounts: Array<AccountEntry>): InstructionResult
  /**
   * Execute a single instruction and assert a set of checks.
   * **Throws** with a descriptive message if any check fails.
   *
   * @param checks - Array produced by the `check*` factory functions.
   */
  processAndValidateInstruction(instruction: JsInstruction, accounts: Array<AccountEntry>, checks: Array<JsCheck>): InstructionResult
  /**
   * Execute a chain of instructions, forwarding account state between steps.
   * Returns the `InstructionResult` for the **last** instruction.
   */
  processInstructionChain(instructions: Array<JsInstruction>, accounts: Array<AccountEntry>): InstructionResult
  /**
   * Execute a chain and assert checks on the final result.
   * **Throws** if any check fails.
   */
  processAndValidateInstructionChain(instructions: Array<JsInstruction>, accounts: Array<AccountEntry>, checks: Array<JsCheck>): InstructionResult
  /**
   * Execute multiple instructions as a single **transaction** (atomic).
   *
   * Unlike `processInstructionChain`, this respects Solana's transaction
   * semantics: if any instruction fails, the entire transaction is rolled
   * back and `success` will be `false`.
   *
   * Returns a `TransactionResult` that also reports which instruction failed.
   */
  processTransactionInstructions(instructions: Array<JsInstruction>, accounts: Array<AccountEntry>): TransactionResult
  /**
   * Override the compute-unit limit for all subsequent executions.
   * Default: 1,400,000 CUs.
   */
  setComputeUnitLimit(limit: number): void
  /** Read the current compute-unit limit. */
  getComputeUnitLimit(): number
  /**
   * Advance the simulated clock to the given slot.
   *
   * Updates `Clock.slot`, `Clock.epoch`, `Clock.leaderScheduleEpoch`,
   * and the `SlotHashes` sysvar to match.
   */
  warpToSlot(slot: bigint): void
  /** Read the current simulated slot. */
  getSlot(): bigint
  /**
   * Set `Clock.unixTimestamp`.
   *
   * Useful for programs that branch on the wall-clock time.
   */
  setClockUnixTimestamp(unixTimestamp: number): void
  /** Read the current simulated `Clock.unixTimestamp`. */
  getClockUnixTimestamp(): number
  /** Set `Clock.epoch`. */
  setEpoch(epoch: bigint): void
  /** Read the current simulated epoch. */
  getEpoch(): bigint
  /**
   * Calculate the minimum lamports needed for rent exemption given `dataLen`.
   *
   * ```ts
   * const lamports = mollusk.getRentMinimumBalance(165); // e.g. token account
   * ```
   */
  getRentMinimumBalance(dataLen: number): bigint
  /**
   * Deactivate a feature by its feature-gate public key (base58).
   *
   * Useful for testing program behaviour under older feature sets.
   *
   * ```ts
   * mollusk.deactivateFeature('someFeaturePubkey...');
   * ```
   */
  deactivateFeature(featureId: string): void
  /**
   * Load the bundled SPL Token program into this harness.
   *
   * After calling this, any instruction that CPIs into SPL Token will work
   * without needing to provide the program account or any `.so` file.
   *
   * ```ts
   * const svm = new MolluskSvm(MY_PROGRAM_ID, 'target/deploy/my_program');
   * svm.addSplToken();
   * ```
   */
  addSplToken(): void
  /** Load the bundled SPL Token-2022 program into this harness. */
  addSplToken2022(): void
  /** Load the bundled SPL Associated Token Account program into this harness. */
  addAssociatedToken(): void
  /** Load the bundled SPL Memo program into this harness. */
  addMemo(): void
}
/**
 * Stateful wrapper around `MolluskSvm` with an in-memory account store.
 *
 * Unlike `MolluskSvm`, you **do not** pass accounts on every call — the
 * context automatically loads, tracks, and persists account state between
 * instruction executions.
 *
 * State is only written back after a **successful** execution.  A failing
 * instruction leaves the store unchanged.
 *
 * ```ts
 * import { MolluskContext, systemAccount, checkSuccess } from 'svmforge';
 *
 * const ctx = MolluskContext.createDefault();
 *
 * // Seed initial account state
 * ctx.setAccount(ALICE, systemAccount(1_000_000_000n));
 * ctx.setAccount(BOB,   systemAccount(0n));
 *
 * // No need to pass accounts — the context handles it
 * ctx.processInstruction(transferIx);
 *
 * // Inspect resulting state
 * console.log(ctx.getAccount(BOB)?.lamports);
 * ```
 */
export declare class MolluskContext {
  /**
   * Create a stateful context loaded with a specific BPF program.
   *
   * @param programId   - Base58 public key of the program under test.
   * @param programPath - Path to the compiled ELF without the `.so` extension.
   */
  constructor(programId: string, programPath: string)
  /** Create a stateful context with no custom program (builtins only). */
  static createDefault(): MolluskContext
  /** Seed or overwrite an account in the store. */
  setAccount(pubkey: string, account: JsAccount): void
  /**
   * Read the current state of an account from the store.
   * Returns `null` if the account has not been set.
   */
  getAccount(pubkey: string): JsAccount | null
  /** Return all (pubkey, account) pairs currently in the store. */
  getAllAccounts(): Array<AccountEntry>
  /**
   * Execute an instruction.  Account state is loaded from — and written
   * back to — the store automatically on success.
   */
  processInstruction(instruction: JsInstruction): InstructionResult
  /**
   * Execute an instruction and assert checks. **Throws** if any check fails.
   *
   * Note: account state is persisted before checks are evaluated.
   * A failing check means your assertion was wrong, not that the
   * instruction failed — check `result.success` first if needed.
   */
  processAndValidateInstruction(instruction: JsInstruction, checks: Array<JsCheck>): InstructionResult
  /** Execute a chain of instructions, forwarding account state between steps. */
  processInstructionChain(instructions: Array<JsInstruction>): InstructionResult
  /** Execute multiple instructions as a single atomic transaction. */
  processTransactionInstructions(instructions: Array<JsInstruction>): TransactionResult
  /** Override the compute-unit limit for this context. */
  setComputeUnitLimit(limit: number): void
  /** Advance the simulated clock to the given slot. */
  warpToSlot(slot: bigint): void
  /** Set `Clock.unixTimestamp`. */
  setClockUnixTimestamp(unixTimestamp: number): void
  /** Calculate the minimum lamports for rent exemption given `dataLen`. */
  getRentMinimumBalance(dataLen: number): bigint
  /** Load the bundled SPL Token program into this context. */
  addSplToken(): void
  /** Load the bundled SPL Token-2022 program into this context. */
  addSplToken2022(): void
  /** Load the bundled SPL Associated Token Account program into this context. */
  addAssociatedToken(): void
  /** Load the bundled SPL Memo program into this context. */
  addMemo(): void
}
